### ISSUE TITLE
Support function-like macros with no arguments

### ISSUE THREAD

**Issue by equal-l2** [maekawatoshiki/qcc#17]
FreeBSD's `sys/cdefs.h` (needed by `stdio.h`) contains a macro:
```c
#define __unreachable() ((void)0)
```

This is currently not supported and QCC claims `expected ','`.

FYI function-like macros with no argument is sometimes preferred to regular macros.
See http://stackoverflow.com/questions/4251005/ .

**Comment by maekawatoshiki** [comment]
- this problem solved.
