### ISSUE TITLE
More accurate implementation for array subscript operator

### ISSUE THREAD

**Issue by equal-l2** [maekawatoshiki/qcc#22]
According to C standard, this code is well-formed but QCC hasn't support some part yet.

```c
int a[] = {1,2,3,4,5};
a[0]; // of course this has no problem.
0[a]; // this is also good, though QCC hasn't supported yet.
'\0'[a] // even this is well-formed (at least under ASCII), though QCC hasn't supported yet.
```

According to [C89](http://read.pudn.com/downloads133/doc/565041/ANSI_ISO%2B9899-1990%2B[1].pdf), subscript operator `E1[E2]` is identical to `(*(E1+(E2)))`.
According to [C99](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) and [C11](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf), it is identical to `(*((E1)+(E2)))`.

Replacing array expression might be needed.

**Comment by maekawatoshiki** [comment]
I knew that. 
But I don't know a good way to implement..

**Comment by equal-l2** [comment]
Would you explain how lexer processes an array subscription, for example `a[3]`?

**Comment by maekawatoshiki** [comment]
Lexer just separates ``a[3]`` into tokens ``a, [, 3, ]``

**Comment by equal-l2** [comment]
Well, I have no idea why I've thought lexer knows semantics.
That is the work for the parser, of course.

**Comment by maekawatoshiki** [comment]
If anything, code-generator knows semantics. parser just conversion tokens into AST mechanically

**Comment by equal-l2** [comment]
Oh, I misunderstood about that.

**Comment by maekawatoshiki** [comment]
BTW, QCC's source code is not beautiful. it's **spaghetti code**.
Can you help me refactor QCC source code?

**Comment by maekawatoshiki** [comment]
After refactoring, we can think about this issue comfortably.

**Comment by equal-l2** [comment]
It's only you who knows the whole part of QCC.
I might be able to help you in some part, but not in very large part.

**Comment by maekawatoshiki** [comment]
OK. I accept even some part.

**Comment by maekawatoshiki** [comment]
Hello. 
I felt like wanting to fix this problem. 
In this week, I'll do.
