### ISSUE TITLE
Escape sequences aren't handled correctly

### ISSUE THREAD

**Issue by equal-l2** [maekawatoshiki/qcc#4]
Any escape sequences (e.g. `\n`,`\r`) are output as typical characters.

Test code:
```c
#include <stdio.h>
int main(){
  printf("hello world\n");
}
```

Expected output:
```
hello world
```

Actual output:
```
hello world\n
```

**Comment by maekawatoshiki** [comment]
I knew that. I wanna implement escape charactors ASAP...

**Comment by equal-l2** [comment]
Thanks for replying.
I'm looking forward to escape sequences being implemented.

You may want to use Github's "project" feature to show you're conscious of escape sequences problem.

**Comment by maekawatoshiki** [comment]
OK. Maybe escape characters will be implemented soon.

**Comment by maekawatoshiki** [comment]
Support escape characters in part from [](https://github.com/maekawatoshiki/qcc/commit/9f3e65f983594cc64dc52f07a9171854dbd88cd1)

**Comment by maekawatoshiki** [comment]
Support escape characters in part from [escape support](https://github.com/maekawatoshiki/qcc/commit/9f3e65f983594cc64dc52f07a9171854dbd88cd1)

**Comment by equal-l2** [comment]
Looks good.
