### ISSUE TITLE
Migration to newer LLVM

### ISSUE THREAD

**Issue by equal-l2** [maekawatoshiki/qcc#9]
I heard you were planning to migrate LLVM 3.8 on https://github.com/maekawatoshiki/qcc/pull/8#issuecomment-271790855.

How is it going?

Since homebrew (macOS community-driven package manager) only support LLVM 3.7 and higher now, I cannot try qcc.

**Comment by maekawatoshiki** [comment]
Sorry. I couldn't migrate because I was busy:(
I'm happy if you migrate to llvm 3.8
